//Stock productos
const stockProductos = [
    {
      //Zapatillas
      id: 1,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 6500,
      img: "Imagenes/productos/zapatillas/1.jpg",
    },
    {
      id: 2,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 3300,
      img: "Imagenes/productos/zapatillas/2.jpg",
    },
    {
      id: 3,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 3500,
      img: "Imagenes/productos/zapatillas/3.jpg",
    },
    {
      id: 4,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 3100,
      img: "Imagenes/productos/zapatillas/4.jpg",
    },
    {
      id: 5,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 2800,
      img: "Imagenes/productos/zapatillas/5.jpg",
    },
    {
      id: 6,
      nombre: "Nike AIR",
      cantidad: 1,
      desc: "38-40-42",
      precio: 2400,
      img: "Imagenes/productos/zapatillas/6.jpg", 
    },
    //Camperas
    {
      id: 7,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 6500,
      img: "Imagenes/productos/camperas/1.jpg",
    },
    {
      id: 8,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 3500,
      img: "Imagenes/productos/camperas/2.jpg",
    },
    {
      id: 9,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 4500,
      img: "Imagenes/productos/camperas/3.jpg", 
    },
    {
      id: 10,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 3800,
      img: "Imagenes/productos/camperas/4.jpg",
    },
    {
      id: 11,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 4200,
      img: "Imagenes/productos/camperas/5.jpg",
    },
    {
      id: 12,
      nombre: "Campera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 6500,
      img: "Imagenes/productos/camperas/6.jpg",
    },
    //Remeras
    {
      id: 13,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 540,
      img: "Imagenes/productos/remeras/1.jpg",
    },
    {
      id: 14,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 400,
      img: "Imagenes/productos/remeras/2.jpg",
    },
    {
      id: 15,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 230,
      img: "Imagenes/productos/remeras/3.jpg",
    },
    {
      id: 16,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 450,
      img: "Imagenes/productos/remeras/4.jpg",
    },
    {
      id: 17,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 940,
      img: "Imagenes/productos/remeras/5.jpg",
    },
    {
      id: 18,
      nombre: "Remera",
      cantidad: 1,
      desc: "M-L-XL",
      precio: 120,
      img: "Imagenes/productos/remeras/6.jpg",
    },
  ];